interface DetectionScripts {
  "lint"?: string;
  "lint:css"?: string;
  "test"?: string;
  "typecheck"?: string;
}

interface ESLintDetection {
  hasESLint: boolean;
}

interface GitHooksConfig {
  enabled: boolean;
  eslint: boolean;
  stylelint: boolean;
  /** Enable Tailwind ESLint validation (replaces shell scripts for CSS validation). Defaults to false. */
  tailwind?: boolean;
  typescript: boolean;
}

interface HookGenerationOptions {
  detection: ProjectDetection;
  /** New config-based generation */
  gitHooks?: GitHooksConfig;
}

interface ProjectDetection {
  eslint: ESLintDetection;
  packageManager: string;
  scripts: DetectionScripts;
  stylelint: { hasStylelint: boolean };
  typescript: TypeScriptDetection;
}

interface TypeScriptDetection {
  hasTypeScript: boolean;
}

/**
 * Generate complete pre-commit hook content
 * @param options - Hook generation options
 * @param options.detection - Project detection results
 * @param options.gitHooks - Git hooks configuration from CLI
 * @param options.gitHooks.tailwind - Enable Tailwind ESLint validation (replaces shell scripts)
 * @returns Complete pre-commit hook bash script
 */
export function generatePreCommitHook(options: HookGenerationOptions): string {
  const {
    detection,
    gitHooks
  } = options;

  // Use new config-based approach if gitHooks is provided
  const useTypescript = gitHooks?.typescript ?? detection.typescript.hasTypeScript;
  const useEslint = gitHooks?.eslint ?? detection.eslint.hasESLint;
  const useStylelint = gitHooks?.stylelint ?? detection.stylelint?.hasStylelint ?? false;
  const useTailwind = gitHooks?.tailwind ?? false;

  const sections = [ String.raw`#!/bin/bash

# Pre-commit hook with automatic code validation
# Generated by claude-workflow

# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
`];

  // Project structure update (always included)
  sections.push(generateProjectStructureSection());

  // TypeScript validation
  if (useTypescript) {
    sections.push(generateTypescriptSection(detection));
  }

  // ESLint validation
  if (useEslint) {
    sections.push(generateESLintSection(detection));
  }

  // Stylelint validation
  if (useStylelint) {
    sections.push(generateStylelintSection(detection));
  }

  // Tailwind CSS validation via ESLint
  if (useTailwind) {
    sections.push(generateTailwindLintSection(detection));
  }

  // Exit successfully
  sections.push("exit 0\n");

  return sections.join("\n");
}

/**
 * Generate Stylelint validation section for pre-commit hook
 * Runs Stylelint on CSS files based on config presence
 * @param detection - Project detection results
 * @returns Bash script section for Stylelint checking
 */
function generateStylelintSection(detection: ProjectDetection): string {
  const { packageManager, scripts } = detection;

  // Prefer npm script if available - runs on CSS files
  if (scripts["lint:css"] !== undefined) {
    return `
# Stylelint validation (entire repo)
printf "\${YELLOW}Running Stylelint on entire repository...\${NC}\\n"
if command -v ${packageManager} &> /dev/null; then
    if ! ${packageManager} run lint:css; then
        printf "\${RED}❌ Stylelint validation failed\${NC}\\n"
        printf "\${YELLOW}Try running: ${packageManager} run lint:css:fix\${NC}\\n"
        exit 1
    fi
    printf "\${GREEN}✅ Stylelint validation passed\${NC}\\n"
else
    printf "\${YELLOW}⚠️ ${packageManager} not found, skipping Stylelint check\${NC}\\n"
fi
`;
  }

  // Fall back to npx stylelint command (uses local install from node_modules)
  return `
# Stylelint validation (entire repo)
printf "\${YELLOW}Running Stylelint on entire repository...\${NC}\\n"
if npx stylelint --version &> /dev/null; then
    if ! npx stylelint "**/*.css" "**/*.scss"; then
        printf "\${RED}❌ Stylelint validation failed\${NC}\\n"
        printf "\${YELLOW}Try running: npx stylelint \\"**/*.css\\" \\"**/*.scss\\" --fix\${NC}\\n"
        exit 1
    fi
    printf "\${GREEN}✅ Stylelint validation passed\${NC}\\n"
else
    printf "\${YELLOW}⚠️ stylelint not found (install with: npm install -D stylelint)\${NC}\\n"
fi
`;
}

/**
 * Generate Tailwind ESLint validation section for pre-commit hook
 * Runs ESLint with Tailwind plugin rules to enforce design token usage
 * @param detection - Project detection results
 * @returns Bash script section for Tailwind linting
 */
function generateTailwindLintSection(detection: ProjectDetection): string {
  const { packageManager, scripts } = detection;

  // Prefer npm script if available
  if (scripts.lint !== undefined) {
    return `
# Tailwind CSS validation via ESLint
printf "\${YELLOW}Running Tailwind CSS validation...\${NC}\\n"
if command -v ${packageManager} &> /dev/null; then
    # ESLint with Tailwind plugin checks for:
    # - no-arbitrary-value: Enforces design token usage
    # - no-contradicting-classname: Prevents conflicting utilities
    # - classnames-order: Ensures consistent class ordering
    if ! ${packageManager} run lint; then
        printf "\${RED}❌ Tailwind CSS validation failed\${NC}\\n"
        printf "\${YELLOW}Check for arbitrary values (e.g., text-[#ff0000]) - use design tokens instead\${NC}\\n"
        exit 1
    fi
    printf "\${GREEN}✅ Tailwind CSS validation passed\${NC}\\n"
else
    printf "\${YELLOW}⚠️ ${packageManager} not found, skipping Tailwind check\${NC}\\n"
fi
`;
  }

  // Fall back to npx eslint command
  return `
# Tailwind CSS validation via ESLint
printf "\${YELLOW}Running Tailwind CSS validation...\${NC}\\n"
if npx eslint --version &> /dev/null; then
    if ! npx eslint --ext .js,.jsx,.ts,.tsx,.vue .; then
        printf "\${RED}❌ Tailwind CSS validation failed\${NC}\\n"
        printf "\${YELLOW}Check for arbitrary values - use design tokens instead\${NC}\\n"
        exit 1
    fi
    printf "\${GREEN}✅ Tailwind CSS validation passed\${NC}\\n"
else
    printf "\${YELLOW}⚠️ eslint not found (install with: npm install -D eslint)\${NC}\\n"
fi
`;
}

/**
 * Generate ESLint validation section for pre-commit hook
 * Runs ESLint on the entire repository, not just staged files
 * @param detection - Project detection results
 * @returns Bash script section for ESLint checking
 */
function generateESLintSection(detection: ProjectDetection): string {
  const { packageManager, scripts } = detection;

  // Prefer npm script if available - runs on whole repo
  if (scripts.lint !== undefined) {
    return `
# ESLint validation (entire repo)
printf "\${YELLOW}Running ESLint on entire repository...\${NC}\\n"
if command -v ${packageManager} &> /dev/null; then
    if ! ${packageManager} run lint; then
        printf "\${RED}❌ ESLint validation failed\${NC}\\n"
        printf "\${YELLOW}Try running: ${packageManager} run lint:fix\${NC}\\n"
        exit 1
    fi
    printf "\${GREEN}✅ ESLint validation passed\${NC}\\n"
else
    printf "\${YELLOW}⚠️ ${packageManager} not found, skipping ESLint check\${NC}\\n"
fi
`;
  }

  // Fall back to npx eslint command (uses local install from node_modules)
  return `
# ESLint validation (entire repo)
printf "\${YELLOW}Running ESLint on entire repository...\${NC}\\n"
if npx eslint --version &> /dev/null; then
    if ! npx eslint .; then
        printf "\${RED}❌ ESLint validation failed\${NC}\\n"
        printf "\${YELLOW}Try running: npx eslint --fix .\${NC}\\n"
        exit 1
    fi
    printf "\${GREEN}✅ ESLint validation passed\${NC}\\n"
else
    printf "\${YELLOW}⚠️ eslint not found (install with: npm install -D eslint)\${NC}\\n"
fi
`;
}

/**
 * Generate project structure update section for pre-commit hook
 * @returns Bash script section for project structure update
 */
function generateProjectStructureSection(): string {
  return `
# Update project structure in .claude/project-structure.md
# This happens for ALL branches (main and worktrees)
CHANGED_FILES=$(git diff --cached --name-status | grep -E '^[AD]' || true)

if [ -n "$CHANGED_FILES" ]; then
    printf "\${YELLOW}Updating project structure in .claude/project-structure.md...\${NC}\\n"

    # Run the update script if it exists
    if [ -f "scripts/update-project-structure.js" ]; then
        node scripts/update-project-structure.js

        # Stage the updated project-structure.md if it was modified
        if git diff --name-only | grep -q ".claude/project-structure.md"; then
            git add .claude/project-structure.md
            printf "\${GREEN}✅ Project structure updated and staged\${NC}\\n"
        fi
    fi
fi
`;
}


/**
 * Generate TypeScript validation section for pre-commit hook
 * Runs TypeScript type checking on the entire repository
 * @param detection - Project detection results
 * @returns Bash script section for TypeScript checking
 */
function generateTypescriptSection(detection: ProjectDetection): string {
  const { packageManager, scripts } = detection;

  // Prefer npm script if available - runs on whole repo via tsconfig.json
  if (scripts.typecheck !== undefined) {
    return `
# TypeScript type checking (entire repo)
printf "\${YELLOW}Running TypeScript type checking on entire repository...\${NC}\\n"
if command -v ${packageManager} &> /dev/null; then
    if ! ${packageManager} run typecheck; then
        printf "\${RED}❌ TypeScript type checking failed\${NC}\\n"
        exit 1
    fi
    printf "\${GREEN}✅ TypeScript validation passed\${NC}\\n"
else
    printf "\${YELLOW}⚠️ ${packageManager} not found, skipping TypeScript check\${NC}\\n"
fi
`;
  }

  // Fall back to npx tsc command (uses local install from node_modules)
  return `
# TypeScript type checking (entire repo)
printf "\${YELLOW}Running TypeScript type checking on entire repository...\${NC}\\n"
if npx tsc --version &> /dev/null; then
    if ! npx tsc --noEmit; then
        printf "\${RED}❌ TypeScript type checking failed\${NC}\\n"
        exit 1
    fi
    printf "\${GREEN}✅ TypeScript validation passed\${NC}\\n"
else
    printf "\${YELLOW}⚠️ typescript not found (install with: npm install -D typescript)\${NC}\\n"
fi
`;
}
