#!/usr/bin/env node

import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

// Script to generate project structure in a separate file
// This creates/updates .claude/project-structure.md with the current project structure

const PROJECT_STRUCTURE_FILE = ".claude/project-structure.md";
const IGNORED_DIRS = new Set([
  ".cache",
  ".DS_Store",
  ".git",
  ".next",
  ".turbo",
  ".vercel",
  "build",
  "coverage",
  "dist",
  "node_modules",
  "out"
]);

const IGNORED_FILES = new Set([
  "*.lock",
  "*.log",
  ".DS_Store",
  "package-lock.json",
  "pnpm-lock.yaml",
  "Thumbs.db",
  "yarn.lock"
]);

const MAX_DEPTH = 4;

function generateProjectStructure(dir = ".", prefix = "", _isLast = true, depth = 0, maxDepth = MAX_DEPTH): string {
  if (depth > maxDepth) return "";

  let structure = "";
  const items = fs.readdirSync(dir).toSorted((a: string, b: string) => {
    // Directories first, then files
    const aIsDir = fs.statSync(path.join(dir, a)).isDirectory();
    const bIsDir = fs.statSync(path.join(dir, b)).isDirectory();
    if (aIsDir && !bIsDir) return -1;
    if (!aIsDir && bIsDir) return 1;
    return a.localeCompare(b);
  });

  const filteredItems = items.filter((item: string) => {
    const itemPath = path.join(dir, item);
    return !shouldIgnore(itemPath, item);
  });

  for (let index = 0; index < filteredItems.length; index += 1) {
    const item = filteredItems[index];
    if (item === undefined) continue;

    const itemPath = path.join(dir, item);
    const isLastItem = index === filteredItems.length - 1;
    const stats = fs.statSync(itemPath);

    // Add tree characters
    const connector = isLastItem ? "└── " : "├── ";
    const extension = isLastItem ? "    " : "│   ";

    if (stats.isDirectory()) {
      structure += `${prefix}${connector}${item}/\n`;
      structure += generateProjectStructure(
        itemPath,
        prefix + extension,
        isLastItem,
        depth + 1,
        maxDepth
      );
    } else {
      // Add file with brief description if it's important
      let description = "";
      if (item === "package.json") description = " # Project configuration";
      if (item === "CLAUDE.md") description = " # Claude instructions (auto-managed)";
      if (typeof item === "string" && (item.endsWith(".config.js") || item.endsWith(".config.ts"))) {
        description = " # Configuration file";
      }

      structure += `${prefix}${connector}${item}${description}\n`;
    }
  }

  return structure;
}

function shouldIgnore(itemPath: string, itemName: string): boolean {
  // Check if directory should be ignored
  if (IGNORED_DIRS.has(itemName)) return true;

  // Check if file matches ignored patterns
  for (const pattern of IGNORED_FILES) {
    if (pattern.includes("*")) {
      const regex = new RegExp(pattern.replace("*", ".*"));
      if (regex.test(itemName)) return true;
    } else if (pattern === itemName) {
      return true;
    }
  }

  // Check if path is in gitignore
  try {
    execSync(`git check-ignore "${itemPath}"`, { stdio: "pipe" });
    return true; // If command succeeds, file is ignored
  } catch {
    return false; // File is not ignored
  }
}

function updateProjectStructure(): void {

  const structureFile = path.join(process.cwd(), PROJECT_STRUCTURE_FILE);
  const claudeDir = path.dirname(structureFile);

  // Ensure .claude directory exists
  if (!fs.existsSync(claudeDir)) {
    fs.mkdirSync(claudeDir, { recursive: true });
  }

  // Generate new structure
  const newStructure = generateProjectStructure();

  // Create the content for project-structure.md
  const content = `# Project Structure\n\nAuto-generated project structure (updated on commit).\n\n\`\`\`\n${newStructure}\`\`\`\n\n<!-- This file is auto-generated by pre-commit hook. Do not edit manually. -->\n`;

  // Write the structure file
  fs.writeFileSync(structureFile, content);

  console.log(`✅ Updated project structure in ${PROJECT_STRUCTURE_FILE}`);
}

// Main execution

if (process.argv[1] === new URL(import.meta.url).pathname) {
  updateProjectStructure();
}